Improves pickle support for HTTPException
Previously, a HTTPException(status_code=404) or similar would be picklable,
but error on deserialization:

TypeError: HTTPException.__init__() missing 1 required positional argument: 'status_code'

This affected both pickle and cloudpickle and libraries making use of them to pass
around exceptions between different processes.